// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhBSb9TYzGtepoPlOMvCOf3MUTyxxZhP4',
    appId: '1:294264122438:android:63c9df04deda8f98e7ae47',
    messagingSenderId: '294264122438',
    projectId: 'flutter--map-80809',
    databaseURL: 'https://flutter--map-80809-default-rtdb.firebaseio.com',
    storageBucket: 'flutter--map-80809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBlT8GeEysN2-fwXCwzu7_pNGFcT3Wbek',
    appId: '1:294264122438:ios:006789d51acb06a8e7ae47',
    messagingSenderId: '294264122438',
    projectId: 'flutter--map-80809',
    databaseURL: 'https://flutter--map-80809-default-rtdb.firebaseio.com',
    storageBucket: 'flutter--map-80809.appspot.com',
    iosClientId: '294264122438-oie5pjrgdgllohq51gvfqj1j2lkoncnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFinalApp',
  );
}
